config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'questions#index'
  resources :questions do
    resources :responses
  end

  #do I need nested routes?
  #get rid of extra ones eventually
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :content, :option_1, :option_2, :photo_1, :photo_2, :presence => true
  has_many :responses
  has_many :users, through: :responses
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :responses
  has_many :questions, through: :responses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
    @response = Response.new
  end
  def new
    @question = Question.new
  end

  def create
    @questions = Question.all
    @question = Question.new(question_params)
    @response = Response.new
    if @question.save
      flash[:notice] = "Question successfully added!"
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:content, :option_1, :option_2, :photo_1, :photo_2)
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def create

    @question = Question.find(params[:question_id])
    @response = @question.responses.new(option_1: response_params[:option_1], option_2: response_params[:option_2], user_id: current_user.id)
    if @response.save
      flash[:notice] = "You voted!"
      @question_response = nil;
      if @question.responses.where(user_id: current_user.id)[0].option_1
        @question_response = @question.option_1
      else
        @question_response = @question.option_2
      end
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  def edit
    @question = Question.find(params[:question_id])
    @response = Response.find(params[:id])
  end

  def update
    @question = Question.find(params[:question_id])
    @response = Response.find(params[:id])
    if comment_params[:comment] != "" && @response.update(comment_params)
      flash[:notice] = "You left a comment!"
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      flash[:notice] = 'nope'
      redirect_to root_path
    end
  end

private

  def response_params
    params.require(:response).permit(:option_1, :option_2)
  end

  def comment_params
    params.require(:response).permit(:comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WouldYouRather</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-faded">
      <%= link_to "Log-in", new_user_session_path %> | <%= link_to "Signup", new_user_registration_path %> | <%= link_to "Log-out", destroy_user_session_path, method: "delete" %>
    </nav>
    <div class="container">
      <%= flash[:notice] %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question, remote:true do |f| %>
  <%= f.label "Your Question" %>
  <%= f.text_field :content %>
  <%= f.label "Option 1" %>
  <%= f.text_field :option_1 %>
  <%= f.label "Photo 1" %>
  <%= f.text_field :photo_1 %>
  <%= f.label "Option 2" %>
  <%= f.text_field :option_2 %>
  <%= f.label "Photo 2" %>
  <%= f.text_field :photo_2 %>
  <%= f.submit "Create Question" %>
<% end %>

app/views/questions/_render_question.html.erb
    <%= form_for [@question, @response], remote: true do |f| %>
      <div class="col-md-4">
        <%= image_tag @question.photo_1 %>
        <%= f.label @question.option_1 %>
        <br>
        <% if current_user && !current_user.questions.include?(@question) %>
          <div class="remove_checkbox_<%= @question.id %>">

            <%= f.check_box :option_1, {}, true, false %>
          </div>
        <% end %>

      </div>
      <div class="col-md-4">
        <div id="mid_column_<%= @question.id %>">
          <h3><%= @question.content %></h3>
          <% if current_user && current_user.questions.include?(@question) %>
          <div id="remove_@question_<%= @question.id %>" class="alignCenter">

            <%= @question.option_1 %>:
            <% if @question.responses.group(:option_1).count[true] %>
              <%= @question.responses.group(:option_1).count[true] %>
            <% else %>
              0
            <% end %>

            <%= @question.option_2 %>:
            <% if @question.responses.group(:option_2).count[true] %>
              <%= @question.responses.group(:option_2).count[true] %>
            <% else %>
              0
            <% end %>
          </div>
          <% if @question.responses.where(user_id: current_user.id)[0].option_1 %>
            <p>You voted for <%= @question.option_1 %></p>
          <% elsif @question.responses.where(user_id: current_user.id)[0].option_2 %>
            <p>You voted for <%= @question.option_2 %></p>
          <% else %>
            <p>Vote!</p>
          <% end %>
          <% if current_user && !current_user.questions.include?(@question) %>
            <div id="edit_button_<%= @question.id %>">
              <%= link_to "Comment", edit_question_response_path(@question, @question.responses.where(user_id: current_user.id).last),:class => "btn btn-default", remote: true %>
            </div>
            <% end %>
          <% if @question.responses.where(user_id: current_user.id) %>
            <% @question.responses.last.comment %>
          <% end %>
          <% end %>
        </div>

      <div id="responses_<%= @question.id %>">
        <% @question.responses.where("comment is NOT NULL and comment != ''").order(created_at: :desc).limit(5).each do |response| %>
          <% if response.comment %>
          <p><%= response.comment %></p>
          <% end %>
        <% end %>
      </div>
    </div>

      <div class="col-md-4">
        <%= image_tag @question.photo_2 %>
        <%= f.label @question.option_2 %>
        <br>
        <% if current_user && !current_user.questions.include?(@question) %>
          <div class="remove_checkbox_<%= @question.id %>">
            <%= f.check_box :option_2, {}, true, false  %>
          </div>
        <% end %>
      </div>
    </div>
      <div class="row remove_checkbox_<%= @question.id %>">
        <div class="col-md-4">
        </div>
        <% if current_user && !current_user.questions.include?(@question) %>
          <div class="col-md-8">
            <%= f.submit 'Vote' %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div id="comment_<%= @question.id %>">

    </div>

app/views/questions/create.js.erb
$('.question_form').hide()
$('.questionBtn').show()
$('#renderQuestion').prepend(' <%= j render("render_question") %> ')

app/views/questions/index.html.erb
<%= link_to "Add a question", new_question_path, class: "questionBtn", remote: true%>

<div class="question_form">

</div>
<div id="renderQuestion">
  <% @questions.each do |question| %>

    <div class="row">
      <%= form_for [question, @response], remote: true do |f| %>
        <div class="col-md-4">
          <%= image_tag question.photo_1 %>
          <%= f.label question.option_1 %>
          <br>
          <% if current_user && !current_user.questions.include?(question) %>
            <div class="remove_checkbox_<%= question.id %>">
              <%= f.check_box :option_1 %>
            </div>
          <% end %>

        </div>
        <div class="col-md-4">
          <div id="mid_column_<%= question.id %>">
            <h3><%= question.content %></h3>
            <% if current_user && current_user.questions.include?(question) %>
              <div id="remove_question_<%= question.id %>" class="alignCenter">
                <div id="graph_<%= question.id %>">
                  <%= pie_chart({question.option_1 => question.responses.group(:option_1).count[true], question.option_2 => question.responses.group(:option_2).count[true]}) %>
                </div>

                <%= question.option_1 %>:
                <% if question.responses.group(:option_1).count[true] %>
                  <%= question.responses.group(:option_1).count[true] %>
                <% else %>
                  0
                <% end %>
                <%= question.option_2 %>:
                <% if question.responses.group(:option_2).count[true] %>
                  <%= question.responses.group(:option_2).count[true] %>
                <% else %>
                  0
                <% end %>

              </div><!--end of remove question div-->

              <% if question.responses.where(user_id: current_user.id)[0].option_1 %>
                <p>You voted for <%= question.option_1 %></p>
              <% elsif question.responses.where(user_id: current_user.id)[0].option_2 %>
                <p>You voted for <%= question.option_2 %></p>
              <% else %>
                <p>Vote!</p>
              <% end %>
              <% if current_user && !current_user.questions.include?(question) %>
                <div id="edit_button_<%= question.id %>">
                  <%= link_to "Comment", edit_question_response_path(question, question.responses.where(user_id: current_user.id).last),:class => "btn btn-default", remote: true %>
                </div>
                <% end %>
              <% if question.responses.where(user_id: current_user.id) %>
                <% question.responses.last.comment %>
              <% end %>
            <% end %><!--end of if current user conditional-->
          </div><!--end of 'middle column'-->

          <div id="responses_<%= question.id %>">
            <% question.responses.where("comment is NOT NULL and comment != ''").order(created_at: :desc).limit(5).each do |response| %>
              <% if response.comment %>
              <p><%= response.comment %></p>
              <% end %>
            <% end %>
          </div><!--ed of responses div-->

        </div><!--end of column-->

        <div class="col-md-4">
          <%= image_tag question.photo_2 %>
          <%= f.label question.option_2 %>
          <br>
          <% if current_user && !current_user.questions.include?(question) %>
            <div class="remove_checkbox_<%= question.id %>">
              <%= f.check_box :option_2 %>
            </div><!--end of remove checkbox div-->
          <% end %>
        </div><!--end of column -->
      </div><!--end of row-->

        <div class="row remove_checkbox_<%= question.id %>">
          <div class="col-md-4">
          </div><!--end of empty column -->
          <% if current_user && !current_user.questions.include?(question) %>
            <div class="col-md-8">
              <%= f.submit 'Vote' %>
            </div><!-- end of vote column -->
            <% end %>
          <% end %>
        </div><!--end of row-->
  <% end %><!--end of loop -->
</div> <!--render question div>

app/views/questions/new.js.erb
$('.question_form').html('<%= j render("form")  %>');
$('.questionBtn').hide();

app/views/responses/_form.html.erb
<%= form_for [@question, @response], remote: true do |f| %>
  <%= f.label 'EXPLAIN YOURSELF' %>
  <%= f.text_field :comment %>
  <%= f.submit %>
<% end %>

app/views/responses/_graph.html.erb
<%= pie_chart({@question.option_1 => @question.responses.group(:option_1).count[true], @question.option_2 => @question.responses.group(:option_2).count[true]}) %>

app/views/responses/_middle_column.html.erb
<% if current_user && current_user.questions.include?(@question) %>
  <div id="remove_question_<%= @question.id %>" class="alignCenter">
    <div id="graph_<%= @question.id %>">
    </div>
    <h3><%= @question.content %></h3>
    <%= @question.option_1 %>: <%= @question.responses.group(:option_1).count[true] %>
    <%= @question.option_2 %>: <%= @question.responses.group(:option_2).count[true] %>
  </div>
  <% if @question.responses.where(user_id: current_user.id)[0].option_1 %>
    <p>You voted for <%= @question.option_1 %></p>
  <% elsif @question.responses.where(user_id: current_user.id)[0].option_2 %>
    <p>You voted for <%= @question.option_2 %></p>
  <% else %>
    <p>Vote!</p>
  <% end %>
    <div id="edit_button_<%= @question.id %>">
      <%= link_to "Edit", edit_question_response_path(@question, @question.responses.where(user_id: current_user.id).last),:class => "btn btn-default", remote: true %>
    </div>
  <% if @question.responses.where(user_id: current_user.id) %>
    <% @question.responses.last.comment %>
  <% end %>
<% end %>

app/views/responses/_question_response.html.erb
<% @question.responses.where("comment is NOT NULL and comment != ''").order(created_at: :desc).limit(5).each do |response| %>
  <% if response.comment %>
  <p><%= response.comment %></p>
  <% end %>
<% end %>

app/views/responses/_results.html.erb
hey

app/views/responses/_vote_totals.html.erb
<%= @question.option_1 %>:
<% if @question.responses.group(:option_1).count[true] %>
  <%= @question.responses.group(:option_1).count[true] %>
<% else %>
  0
<% end %>
<%= @question.option_2 %>:
<% if @question.responses.group(:option_2).count[true] %>
  <%= @question.responses.group(:option_2).count[true] %>
<% else %>
  0
<% end %>

app/views/responses/create.js.erb
// $('form').remove();
$('#remove_question_<%= @question.id %>').show();
$('.remove_checkbox_<%= @question.id %>').html('')
$('#mid_column_<%= @question.id %>').html('<%= j render("middle_column") %> ').after('<%= j render("graph") %>');
$('#remove_question_<%= @question.id %>').html('<%= j render("vote_totals") %>');

app/views/responses/edit.js.erb
$('#comment_<%= @question.id %>').html('<%= j render("form") %>');
$('#edit_button_<%= @question.id %>').hide();

app/views/responses/update.js.erb
$('#comment_<%= @question.id %>').hide();
$('#responses_<%= @question.id %>').html('<%= j render("question_response") %>');